name: Build Emilia Setup

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download repo
        uses: actions/checkout@v6.0.2

      - name: Python Setup
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12' 

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Download UPX
        shell: pwsh
        run: |
          $output = "upx.zip"
          
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v5.1.0/upx-5.1.0-win64.zip" -OutFile $output
          
          Expand-Archive -Path $output -DestinationPath upx_temp
          
          Move-Item -Path upx_temp/upx-5.1.0-win64/upx.exe -Destination .

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          $LK_PATH = python -c "import livekit; print(list(livekit.__path__)[0])"

          pyinstaller --noconfirm --onedir --windowed `
            --icon "src\icon.ico" `
            --uac-admin `
            --add-data "$LK_PATH\rtc\resources\livekit_ffi.dll;livekit/rtc/resources" `
            --hidden-import "urllib3.contrib.resolver.system" `
            --hidden-import "urllib3.contrib.hface.protocols.http1" `
            --hidden-import "urllib3.contrib.hface.protocols.http2" `
            --hidden-import "livekit.rtc.resources" `
            "src\main.py"

          copy "src\icon.ico" "dist\main\icon.ico"
          xcopy /E /I /H /Y "src\lang" "dist\main\lang"

          if (Test-Path "dist\main\main.exe") {
              Rename-Item -Path "dist\main\main.exe" -NewName "emilia.exe"
          } else {
              exit 1
          }

      - name: Cleanup Junk Files
        run: |
          python clean_dist.py

      - name: Create manifest
        shell: pwsh
        run: |
          python create_manifest.py

      - name: Deploy via SCP
        shell: pwsh
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # 1. Создаем файл ключа
          $keyFile = "id_rsa_deploy"
          Set-Content -Path $keyFile -Value $env:KEY -NoNewline
          
          # Ограничиваем права (для Windows ssh это не критично, но полезно)
          # На Windows это сложнее, поэтому ssh.exe часто ругается на "too open".
          # Но в GitHub Actions обычно работает сразу.

          # 2. Добавляем хост в known_hosts (чтобы не спрашивал yes/no)
          mkdir -p ~/.ssh
          ssh-keyscan -H $env:HOST >> ~/.ssh/known_hosts

          # 3. Заливаем файлы
          # -r : рекурсивно (всю папку)
          # -o StrictHostKeyChecking=no : отключить проверку хоста (на всякий случай)
          # dist/main/* : всё содержимое папки main
          # $env:USER@$env:HOST:/home/user1/emilia/ : куда класть
          
          Write-Host "Начинаю загрузку на VPS..."
          scp -r -i $keyFile -o StrictHostKeyChecking=no dist/main/* $env:USER@$env:HOST:/home/user1/emilia/
          
          # 4. Удаляем ключ
          Remove-Item $keyFile
          
      - name: Build Setup file
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: installer.iss

      - name: Upload installer
        uses: actions/upload-artifact@v6
        with:
          name: Emilia_Installer
          path: EmiliaSetup.exe

      - name: Public release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: EmiliaSetup.exe
          generate_release_notes: true
